files:
  include: 'src/static/**/*.s+(a|c)ss'
  ignore:
  - 'src/static/**/vendor/**/*.*'
formatter: stylish
rules:
  indentation:
    - 2
    - size: 2
  class-name-format:
    - 1
    - convention: strictbem

