# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('identifier', models.TextField()),
                ('parameter_miejsce_badania', models.TextField(default='')),
                ('parameter_rocznik', models.FloatField()),
                ('parameter_wyznanie', models.TextField(default='')),
                ('parameter_jezyk', models.TextField(default='')),
                ('parameter_powiat_urodzenia', models.TextField(default='')),
                ('parameter_waga', models.FloatField()),
                ('parameter_wzrost', models.FloatField()),
                ('parameter_wzrost_od_ziemi_do_podbrodka', models.FloatField()),
                ('parameter_wzrost_od_ziemi_do_mostka', models.FloatField()),
            ],
        ),
    ]
