# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizedimage', '0002_auto_20180124_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pdf_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
