# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizedimage', '0004_auto_20180125_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='')),
                ('card_id', models.IntegerField(db_index=True)),
                ('image_id', models.IntegerField(db_index=True)),
                ('image', models.ImageField(upload_to='')),
                ('parameter_miejsce_badania', models.TextField(db_index=True, default='')),
                ('parameter_data_badania', models.TextField(db_index=True, default='')),
                ('parameter_rocznik', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wyznanie', models.TextField(db_index=True, default='')),
                ('parameter_jezyk', models.TextField(db_index=True, default='')),
                ('parameter_powiat_urodzenia', models.TextField(db_index=True, default='')),
                ('parameter_waga', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost_od_ziemi_do_podbrodka', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost_od_ziemi_do_mostka', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost_do_wzgorka_lonowego', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost_do_kolan', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost_do_kostki', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wzrost_od_ziemi_do_ramienia', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_od_ziemi_do_lokcia', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_od_ziemi_do_nadgarstka', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_od_ziemi_do_konca_palca_srodkowego', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_dlugosc_stopy_od_piety_do_duzego_palca_u_nogi', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_stopy', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_w_barkach', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_klatki_piersiowej', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_glebokosc_klatki_piersiowej', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_w_biodrach', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_dloni', models.FloatField(blank=True, db_index=True, null=True)),
                ('parametr_dlugosc_palca_srodkowego', models.FloatField(blank=True, db_index=True, null=True)),
                ('parametr_wysokosc_twarzy_od_brody_do_poziomu_oczu', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_od_oczu_do_gornej_szczeki', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_wysokosc_nosa', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_nosa_u_podstawy', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_dlugosc_czaszki_od_czola_do_potylicy', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_czaszki_na_wysokosci_oczu', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_szerokosc_czaszki_na_wysokosci_uszu', models.FloatField(blank=True, db_index=True, null=True)),
                ('szerokosc_czola', models.FloatField(blank=True, db_index=True, null=True)),
                ('szerokosc_twarzy', models.FloatField(blank=True, db_index=True, null=True)),
                ('szerokosc_zuchwy', models.FloatField(blank=True, db_index=True, null=True)),
                ('obwod_glowy', models.FloatField(blank=True, db_index=True, null=True)),
                ('obwod_szyi', models.FloatField(blank=True, db_index=True, null=True)),
                ('obwod_piersi', models.FloatField(blank=True, db_index=True, null=True)),
                ('obwod_w_pasie', models.FloatField(blank=True, db_index=True, null=True)),
                ('obwod_bioder', models.FloatField(blank=True, db_index=True, null=True)),
                ('obwod_posladkow', models.FloatField(blank=True, db_index=True, null=True)),
                ('najwiekszy_obwod_ramienia', models.FloatField(blank=True, db_index=True, null=True)),
                ('najwiekszy_obwod_przedramienia', models.FloatField(blank=True, db_index=True, null=True)),
                ('najmniejszy_obwod_przedramienia', models.FloatField(blank=True, db_index=True, null=True)),
                ('najwiekszy_obwod_uda', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_obwod_kolana', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_najwiekszy_obwod_przedudzia', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_najmniejszy_obwod_przedudzia', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_obwod_podbicia_gornego', models.FloatField(blank=True, db_index=True, null=True)),
                ('parameter_obwod_podbicia_dolnego', models.FloatField(blank=True, db_index=True, null=True)),
                ('instytucja', models.TextField(db_index=True, default='')),
            ],
            options={
                'ordering': ['card_id', 'image_id'],
            },
        ),
        migrations.CreateModel(
            name='CardImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('card_images', models.ManyToManyField(to='parametrizedimage.CardImage')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
