# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bible',
            name='pdf_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
